name: "HA Collector"
version: "0.89"
slug: "hacollector"
description: "LG System Aircon (RS485) Collector"
url: "https://github.com/ggulamtggul/hacollector"
image: "ghcr.io/ggulamtggul/hacollector/{arch}"
startup: application
init: false
arch:
  - aarch64
  - amd64
options:
  lg_server_ip: "192.168.0.100"
  lg_server_port: 8899
  mqtt_server: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  rooms:
    - livingroom
    - bedroom
  log_level: "info"
schema:
  lg_server_ip: str
  lg_server_port: int
  mqtt_server: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  rooms:
    - str
  log_level: str
map:
  - config:rw
